name: Deploy (self‑hosted)

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}   # PAT with read:packages

      - name: Pull latest image
        run: |
          IMAGE="ghcr.io/kadvait/devops-demo:latest"
          docker pull $IMAGE

      - name: Deploy with Compose
        run: |
          docker compose pull
          docker compose up -d
